#lang racket
#| 3d-interface.rkt uses the pict3d library to plot points and connections as generated by plato.rkt.
   As of July 2024, pict3d is broken in Ubuntu Linux.

   Written by Patrick King, all rights reserved  |#

(require pict3d)
